sudo: required
services:
  - docker

before_install:
  - docker build -t tvielgouarin/docker-react -f Dockerfile.dev .

script:
  - docker run tvielgouarin/docker-react npm run test -- --coverage

# Deploy to AWS
# deploy:
#   provider: elasticbeanstalk
#   region: "us-west-2"
#   app: "docker"
#   env: "Docker-env"
#   bucket_name: "name-of-the-bucket"
#   bucket_path: "docker"
#   on:
#     branch: master
#   access_key_id: $AWS_ACCESS_KEY
#   secret_access_key:
#     secure: "AWS_SECRET_KEY"
